### ISSUE TITLE
"JBERET000651: The requested permits (%d) is greater than the maximum number of permits (%d) allowed in the thread pool.";

### ISSUE THREAD

**Issue by cedricwalter** [jberet/jsr352#143]
We got this error in openshift 4.0 with quarkus 1.11.0-Final and latest quarkus-jberet

org.jboss.threads.JBossThread.run(JBossThread.java:501)
: java.lang.IllegalStateException: JBERET000651: The requested permits (2) is greater than the maximum number of permits (1) allowed in the thread pool.

Is this something we can solve in application.properties? or in openshift environment?

**Comment by chengfang** [comment]
The error message means batch thread pool does not have sufficient number of threads available. Can you check your batch subsystem config (`subsystem/batch-jberet/thread-pool/max-threads`)?  Are there large number of job executions that may have exhause the pool of threads?

Another fator is, since you're in openshift, is the quota imposed by openshift for the pod. You can try raising the cpu quota and see if that makes a difference.

**Comment by cedricwalter** [comment]
you were right, the quota imposed by openshift for the pod was way too low, setting it to 2000m or 2 cores fixes the issues

```
           resources:
                requests:
                  cpu: 50m
                  memory: 50Mi
                limits:
                  cpu: 2000m
                  memory: 500Mi
```
